Description = "Solus plugin for the Narwhal IRC bot."
License = "Apache-2.0"
Name = "Narwhal Solus Plugin"
Version = 0.1

[Projects]
	[Projects.plugin]
		ConsolidateChildDirs = false
		DisableNestedEnvironment = true
		Destination = "build/solus.so"
		EnableGoModules = true
		Plugin = "go"
		Private = ["github.com"] # Ignore github.com caching since updating against tusk can be time sensitive
		Source = "*.go"
		Type = "plugin"
